### ISSUE TITLE
Wrong hmmlearn usage

### ISSUE THREAD

**Issue by gao462** [RRisto/learning#1]
I was looking for Baum-Welch posts with implementations, and found your web page.
In your Baum-Welch algorithm implementation notebook, you use hmmlearn in a wrong way.
It should be `hmm.MultinomialHMM(n_components=2, n_iter=n_iter, init_params="", params="te", tol=0)` which is the counterpart of your custom implementation. (Error will be very close to 0.)
Your current version `hmm.MultinomialHMM(n_components=2, n_iter=n_iter, init_params=""` will also update initial distribution and early stop which is not in your implementation.

**Comment by RRisto** [comment]
Thanks for the comment. You are correct, made an update :)
